app_dashboard/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

app_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', add_friend, name='add_friend'),
 ]

app_profile/urls.py
from django.conf.urls import url
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
    url(r'^$', index, name='index'),
]

app_status/urls.py
from django.conf.urls import url
from .views import index, add_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
]

project/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
import app_friend.urls as app_friend
import app_profile.urls as app_profile
import app_dashboard.urls as app_dashboard
import app_status.urls as app_status
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^friend/', include(app_friend, namespace='add-friend')),
    url(r'^dashboard/', include(app_dashboard, namespace='dashboard')),
    url(r'^app-profile/', include(app_profile,namespace='app-profile')),
    url(r'^app_status/', include(app_status, namespace='app_status')),
    url(r'^$', RedirectView.as_view(url="/app_status/", permanent="true"), name='app_status'),

]

app_dashboard/models.py
from django.db import models

# Create your models here.

app_friend/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
	name = models.CharField(max_length=27)
	url = models.URLField()
	created_date = models.DateTimeField(auto_now_add=True)

app_profile/models.py
from django.db import models
from datetime import date

# Create your models here.

class Profile(models.Model):
	name = models.CharField(max_length=27)
	gender = models.CharField(max_length=6)
	description = models.TextField(max_length=300)
	email = models.EmailField()

class Expertise(models.Model):
	expertise = models.TextField(max_length=100)

app_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	message = models.CharField(max_length=100)
	created_date = models.DateTimeField(auto_now_add=True)

app_friend/forms.py
from django import forms

class Add_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan URL',
    }
    name_attrs = {
        'type':'text',
    	'class':'form-control',
        'placeholder':'Name'
    }
    url_attrs = {
        'type':'url',
    	'class':'form-control',
        'placeholder':'http://example.com'
    }

    name = forms.CharField(label='Name', required=True, widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label='URL', required=True, widget=forms.TextInput(attrs=url_attrs))

app_status/forms.py
from django import forms
# Create your views here.
class Message_Form(forms.Form):
    attrs = {
        'class': 'form-control'
    }

    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True, max_length=100)

app_dashboard/views.py
from django.shortcuts import render, HttpResponse
from app_status.models import Status
from app_profile.models import Profile
from app_profile.views import mhs_name
from app_friend.models import Friend

# Create your views here.
response = {}

def index(request):
    totalFeed = Status.objects.all().count()
    friends = Friend.objects.all().count()
    profiles = Profile.objects.all().count()

    response['total_feed'] = totalFeed
    response['total_friend'] = friends
    response['latest_post'] = '-'
    response['latest_post_date'] = '-'
    response['name'] = mhs_name

    if(totalFeed != 0):
        s = Status.objects.last()
        response['latest_post'] = s.message
        response['latest_post_date'] = s.created_date

    return render(request, 'app_dashboard.html', response)

app_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Form
from .models import Friend
from urllib.request import urlopen
from urllib.error import URLError

# Create your views here.
response = {}

def index(request):
	friend = Friend.objects.all()
	response['friend'] = friend
	html = 'add_friend.html'
	response['add_form'] = Add_Form
	return render(request, html, response)

def add_friend(request):
	form = Add_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()) and url_is_valid(request.POST['url']):
		response['valid'] = True
		response['name'] = request.POST['name']
		response['url'] = request.POST['url']
		friend = Friend(name=response['name'], url=response['url'])
		friend.save()
		return HttpResponseRedirect('/friend/')
	else:
		response['valid'] = True
		return HttpResponseRedirect('/friend/')

def url_is_valid(url):
    try:
        thepage = urlopen(url)
    except URLError as e:
        return False
    else:
        return True

app_profile/views.py
from django.shortcuts import render
from datetime import date
from .models import Profile, Expertise
# Create your views here.


mhs_name = 'Aviliani Pramestya'
birth_date = date(1997, 12, 4)
mhs_gender = 'Female'
mhs_expertise = ['Python', 'Java', 'Django']
mhs_description = 'We are just what we are'
mhs_email = 'kelompok13@gmail.com'

def index(request):
    profile = Profile(name=mhs_name,gender=mhs_gender, description=mhs_description, email=mhs_email)
    expertise = Expertise(expertise=mhs_expertise)
    response = {'Name': profile.name,'Birthday': birth_date,'Gender':profile.gender, 'Description':profile.description, 'Email': profile.email, 'Expert' : expertise.expertise}
    return render(request, 'app_profile.html', response)

app_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Status
# Create your views here.
response = {}

def index(request):
    html = 'app_status/app_status.html'
    #TODO Implement, isilah dengan 6 kata yang mendeskripsikan anda
    response['author'] = "Aviliani Pramestya"
    status = Status.objects.all().order_by('-created_date')
    response['status'] = status
    html = 'app_status/app_status.html'
    response['message_form'] = Message_Form
    return render(request, html, response)

def add_status(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['message'] = request.POST['message']
        status = Status(message=response['message'])
        status.save()
        html ='app_status/app_status.html'
        render(request, html, response)
        return HttpResponseRedirect('/app_status/')	
    else:        
        return HttpResponseRedirect('/add_status/')	

app_dashboard/templates/app_dashboard.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/statpage.css' %}" />


<h1 id = 'title'> Statistic </h1>
<div class="container-fluid">
  <div class="row align-items-start">
    <div class="col" id="profilebox">
      <img src="https://image.freepik.com/free-vector/vector-illustration-cosmonaut_1441-11.jpg" class="img-fluid" id="profile-pict">
      <h3 id="name">{{ name }}</h3>
    </div>
    <div class="col-8" id="statsbox">
      <h3 id = 'ff'>Friends : {{ total_friend }} People</h3>
      <h3 id = 'ff'>Feeds : {{ total_feed }} Post</h3>
      <h3></h3>
      <h3 id = "latest">Latest Post :</h3>
      <div class="status" id='lpost'>
        <img src="https://image.freepik.com/free-vector/vector-illustration-cosmonaut_1441-11.jpg" class="img-fluid" id="post-pict">
        <div class="post">
            <p>{{ latest_post }}</p>
            <div class="status-with-date">
                Posted on {{ latest_post_date }}
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app_dashboard/templates/partials/footer.html
<p>&copy; Made by Kelompok 13</p>

app_dashboard/templates/partials/header.html
<!-- Fixed navbar -->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
<nav class="navbar navbar-default navbar-static-top">
 <div class="container">
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="{% url 'app_status:index' %}">Ling Kedin</a>
   </div>
   <div id="navbar" class="navbar-collapse collapse">
     <ul class="nav navbar-nav">
       <!-- LINK MENUJU table, dan link menuju home#form -->
       <li><a href="{% url 'app_status:index' %}"> Status </a></li>
       <li><a href="{% url 'app-profile:index' %}"> Profile </a> </li>
       <li><a href="{% url 'add-friend:index' %}"> Friends </a></li>
       <li><a href="{% url 'dashboard:index' %}"> Stats </a> </li>
     </ul>
   </div><!--/.nav-collapse -->
 </div>
</nav>

app_friend/templates/add_friend.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}">
<section name='add-input' id='add-input'>
	<h4>Add Friend</h4>
	<form id='form' method="POST" action="{% url 'add-friend:add_friend' %}">
		{% csrf_token %}
        {{ add_form }}
        <br>
	    <button id="submit" type="submit" class="btn pull-right btn-primary">Add Friend</button>
	</form>
	{% if not valid %}
	<div class="alert alert-danger alert-dismissable">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<strong>Sorry!</strong> You've added an invalid friend.
	</div>
	{% endif %}
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <div class="flex">
            {% if friend %}
                {% for data in friend %}
                    <div class="flex-item">
                        <div class="friends-list">
                            <div class="friend-list-image">
                                <img id="friend-image" src="http://www.sbsc.in/images/dummy-profile-pic.png" alt="profile-image"/>
                            </div>
                            <div class="friend-list-name">
                                {{data.name}}
                            </div>
                            <div class="friend-list-url">
                                <a href="{{ data.url }}" target="_blank">{{ data.url }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</section>
<section name='friend-list' id='friend-list'>
	<h4>List Friend</h4>
	<table class='table table-responsive table-hover'>
		<tbody>
			{% if friend %}
				{% for i in friend %}
				<tr>
					<td> {{ i.name }} </td>
					<td></td>
					<td> <a href="{{ i.url }}">{{ i.url }}</a> </td>
					<td> Added 	{{ i.created_date }} </td>
				</tr>
				{% endfor %}
			{% else %}
			<div class="alert alert-danger text-center">
                <strong>Oops!</strong> You don't have any friends.
            </div>
            {% endif %}
		</tbody>
	</table>
</section>
{% endblock %}

app_profile/templates/app_profile.html
{% extends "base.html" %}
{% block content %}

{% load staticfiles %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/app_profile.css' %}">


<title>Profile</title>
<h1 class="main-title">PROFILE</h1>

<body>
  <div id='profile'>
    <p style="text-align: center"><img class="img-circle" src = 'https://image.freepik.com/free-vector/vector-illustration-cosmonaut_1441-11.jpg' width="200" height="200"></p>
    <h3 class="name">{{ Name }}</h3>


    <table class="profile-table" align="center" width="600" cellpadding="40" cellspacing="20">

            <tr>
    		      <td class="subject">Birthday</td>
    		        <td class="value">{{ Birthday }}</td>
            </tr>
            <tr>
              <td class="subject">Gender</td>
                <td class="value">{{ Gender }}</td>
            </tr>
            <tr>
              <td class="subject">Description</td>
                <td class="value">{{ Description }}</td>
            </tr>
            <tr>
              <td class="subject">E-mail</td>
                <td class="value">{{ Email }}</td>
            </tr>

        <tr>
          <td class="subject">Expertise</td>
          <td class="value-exp">
              {% for ii in Expert %}
              <span class="badge">{{ ii }}
            </span>
          {% endfor %}
        </td>
      </tr>
    </table>
  </div>
</body>


{% endblock %}

app_status/templates/app_status/app_status.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/app_status.css' %}">

<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'app_status:add_status' %}" >
            <h2>Update Status</h2>
            {% csrf_token %}
            {{ message_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Post">
        </form>
    </div>
</section>
<section name = "my-status" id="my-status">
    {% for data in status %}
        <div class="flex-item" style="padding: 10px" id="statuses">
            <div  id = "name">
                <img src="https://image.freepik.com/free-vector/vector-illustration-cosmonaut_1441-11.jpg" id="circular-image">
                <strong>{{author}}</strong>
            </div>

            <div  id = "msg">
                {{data.message}}
            </div>

            <div  id = "time">
                Posted on {{ data.created_date }}
            </div>
        </div>

        <div id="space">
            {{ " " }}
        </div>
    {% endfor %}
</section>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Tugas 1 PPW">
    <meta name="author" content="Kelompok 13">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap css -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Mukta|Quicksand" rel="stylesheet">

    <title>
        Ling Kedin
    </title>
</head>

<body style="background-image: url(https://media.giphy.com/media/bnZIn51bngWAg/giphy.gif);">
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>
    </content>
    <footer style="text-align: center; padding-top: 10px;">
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>